# Simple Redis + RQ setup
version: '3.8'
services:
  pipeline:
    build:
      context: .
      dockerfile: ./devops/Dockerfile
    env_file:
      - ./.env
    depends_on:
      - redis
  redis:
    image: redis:7
    ports:
      - "6379:6379"
