name: 'csc_dbt'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'csc_dbt'

# These paths correspond to the directories where you store
# your dbt models, tests, macros, etc.
model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]

models:
  elementary:
    +schema: elementary
  
  csc_dbt:
    # This is the global default value unless otherwise specified
    # In other words, we'll always materialize tables from our
    # dbt models unless if we're overriding it
    +materialized: table
    
    00-base:
      +schema: base
      +materialized: view
    
    01-staging:
      +schema: staging
      +tags: ["staging"]
    
    # The +enabled config allows us to conditionally run these models
    # In this case, we don't want to run the ML models unless the
    # environment variable RUN_ML_MODELS is set to "true"
    02-analytics:
      +schema: analytics
      +enabled: "{{ var('RUN_ML_MODELS', 'false') == 'true' }}"
    
    03-reporting:
      +schema: reporting
      +materialized: view

vars:
  elementary:
    insert_rows_method: "chunk"
    dbt_artifacts_chunk_size: 1000
    query_max_size: 1000000

flags:
  require_explicit_package_overrides_for_builtin_materializations: false
  source_freshness_run_project_hooks: true
