csc_dbt:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: tmc-changemakers-2025
      dataset: csc_dbt
      threads: 1
      timeout_seconds: 300
      location: US
      priority: interactive
      keyfile: ../service_accounts/tmc-changemakers-2025-a5d74b23cad8.json

      gcs_bucket: csc-scratch
      dataproc_region: us-central1
      submission_method: serverless